#!/bin/sh -e

oldh="$1"
if [ -z "$1" ]; then
    echo "Usage: $0 old_hash [new_hash]"
    echo
    echo "pydiff the changed files between old_hash to new_hash."
    echo "Current HEAD is the default for new_hash."
fi

if [ -z "$2" ]; then
    newh=HEAD
else
    newh="$2"
fi

oldf=`mktemp`
newf=`mktemp`

for f in `git diff --name-only "$newh".."$oldh"`;
do
    if ! echo "$f" | grep -q -E '\.py(.in)?$';
    then
        continue
    fi

    git show "$oldh":"$f" > "$oldf"
    git show "$newh":"$f" > "$newf"
    pydiff --name "$f" "$oldf" "$newf" || :
done

rm "$oldf" "$newf"
